### ISSUE TITLE
Running with nix

### ISSUE THREAD

**Issue by happysalada** [bonfire-networks/bonfire-app#85]
Hi guys, great project!

Here is a Dockerfile I use on production. It uses a multistage build for a tiny image
(I just thought I would put it here for reference, in case you are interested. My app is called union, but you can replace with anything).
I'm posting this, since I'm not yet aware completely of the intricacies of the build of your app. It's for a standard phoenix application.
```
FROM elixir:1.11.4-alpine AS builder

RUN apk add --no-cache \
    # required for bcrypt
    gcc \
    make \
    libc-dev

RUN  mix local.rebar --force && \
    mix local.hex --force

WORKDIR /opt/app
ENV MIX_ENV=prod

FROM builder as deps
COPY mix.* /opt/app/
RUN mix do deps.get --only prod
RUN mix deps.compile --warnings-as-errors

FROM node:15.13.0-alpine as frontend
RUN apk add --no-cache \
    # all these are required to make the imagemin install work
    autoconf \
    automake \
    bash \
    g++ \
    libc6-compat \
    libjpeg-turbo-dev \
    libpng-dev \
    make \
    nasm
RUN npm install -g pnpm

WORKDIR /opt/app
COPY ./assets/package.json /opt/app/
COPY ./assets/pnpm-lock.yaml /opt/app/
COPY --from=deps /opt/app/deps/phoenix /deps/phoenix
COPY --from=deps /opt/app/deps/phoenix_html /deps/phoenix_html
RUN pnpm install
COPY ./assets /opt/app
# needed by purgecss
COPY ./lib/union_web/templates /opt/app
COPY ./lib/union_web/live /opt/app
RUN pnpm deploy

FROM deps as releaser
COPY . /opt/app/
COPY --from=frontend /opt/priv/static ./priv/static
RUN mix do phx.digest, release

# minimal runtime image
FROM alpine:3.13.4 AS runner

RUN apk add \
    # required by erlang
    ncurses-libs \
    # curl is required by the health check
    curl

WORKDIR /opt/app
COPY --from=releaser /opt/app/_build/prod/rel/union .
CMD /opt/app/bin/union start
```

I usually run it with a docker-compose that includes a reverse_proxy (caddy is just to take care of ssl for me)

```
version: "3.7"

networks:
  webnet:
    driver: overlay

services:
  # https://github.com/lucaslorentz/caddy-docker-proxy
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.3.2-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet
    labels:
      caddy.email: raphael@forunion.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any

  web:
    image: "happysalada/union:2021-03-13_12.47.39"
    ports:
      - 4080:80
      - 4369:4369
    volumes:
      - "./uploads:/opt/app/priv/static/uploads"
    networks:
      - webnet
    healthcheck:
      test: curl -sS http://127.0.0.1/login || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - ENV_VAR=${MY_ENV_VAR}
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        monitor: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      labels:
        caddy:
            www.$DOMAIN_NAME
        caddy.reverse_proxy: "{{upstreams 80}}"
        # caddy.tls.ca: https://acme-staging-v02.api.letsencrypt.org/directory

  postgres13:
    image: postgres:13.1-alpine
    volumes:
      - "./postgres13:/var/lib/postgresql/data"
      # by default shared memory is only 64MB
      # shm_size is not available in docker swarm
      # workaround found at
      # https://www.reddit.com/r/docker/comments/dvqh2f/shared_memory_size_in_docker_compose/
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2000000000 # ~2gb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - webnet
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
```

You can run this with 
`docker stack deploy -c ~/docker-compose.yml bonfire`
docker stack is basically the same as docker compose.

I'm happy to discuss any of these.
